= mw-backend-scaleway

A Terraform based link:https://github.com/magic-wormhole[Magic Wormhole] backend deployment on link:https://www.scaleway.com/[Scaleway] infrastructure.

For the given _<Base domain name>_ the following services will be available:

* On the public loadbalancer IP (resolved for `mailbox` and `relay` subdomains:
+

|===
|Port |Service

|4000
|Mailbox Service

|4001
|Relay Service

|4002
|Relay Service via WebSocket
|===

* via SSL/SNI
+

|===
|URL |Service

|https://mailbox.<base domain name>/
|Mailbox Service

|https://relay.<base domain name>/
|Relay Service via WebSocket
|===

* The `<base_domain_name>` resolves to the public ip of the backend server. This is currently used to allow SSH access to the backend server.

== Prerequisites

* A Scaleway account
* The desired base domain name needs to be registered within the Scaleway project (see link:https://www.scaleway.com/en/docs/network/dns-cloud/quickstart/[their documentation])
* Environment Variables
+
[source,shell]
----
export SCW_ACCESS_KEY=<Scaleway acccess key>
export SCW_SECRET_KEY=<Scaleway secret key>
# required for the S3 state storage
export AWS_ACCESS_KEY=<Scaleway acccess key>
export AWS_SECRET_KEY=<Scaleway secret key>
export SCW_DEFAULT_ORGANIZATION_ID=<Scaleway organization id>
export SCW_DEFAULT_PROJECT_ID=<Scaleway project id>
export TF_VAR_base_domain_name=<registered base domain name>
----

== Open issues

* There is no state locking mechanism available for now when using Scaleway S3 for state storage.
